export type Locale = 'en' | 'zh-CN'

export const copy = {
  en: {
    title: 'Sempre — Proxy core lifecycle manager',
    skip: 'Skip to content', navArchitecture: 'Architecture', navPlatforms: 'Platforms', navDocs: 'Docs',
    eyebrow: 'Native lifecycle control plane', tagline: 'Any core. Always current. Always running.',
    lead: 'Install, switch, validate, and supervise proxy cores with one native service and one replaceable Web UI.',
    quickStart: 'Quick start', oneCommand: 'One command, verified release.', checksum: 'SHA-256 verified before execution',
    coreOption: 'Core (optional)', corePlaceholder: 'sing-box@stable', subscriptionOption: 'Subscription URL (optional)', subscriptionPlaceholder: 'https://example.com/subscription',
    uiOption: 'Web UI', uiDefault: 'Automatic: preserve / official', uiOfficial: 'Official UI', uiGitHub: 'GitHub release', uiURL: 'HTTPS ZIP',
    uiSource: 'UI source', uiGitHubPlaceholder: 'owner/repo@stable', uiURLPlaceholder: 'https://example.com/sempre-ui.zip', uiDigest: 'UI SHA-256', uiDigestPlaceholder: '64-character digest',
    inspectScript: 'Inspect script', releaseNote: 'Pre-1.0 software · unsigned binaries · review release notes before privileged installation',
    signalNative: 'Native service managers', signalAtomic: 'Atomic core switching', signalReplaceable: 'Replaceable Web UI', signalCrossPlatform: 'Three operating systems',
    signalNativeDetail: 'Runs through Windows SCM, systemd, and launchd without an extra service wrapper.',
    signalAtomicDetail: 'Validates a new deployment before activation and keeps the last working version for rollback.',
    signalReplaceableDetail: 'Install or replace the Web UI independently without changing the service or managed core.',
    signalCrossPlatformDetail: 'One operating model across Windows, Linux, and macOS on amd64 and arm64.',
    overview: 'Overview', supervisor: 'SUPERVISOR', running: 'Running', activeCore: 'ACTIVE CORE', enterControlPlane: 'ENTER THE CONTROL PLANE',
    sectionControl: '01 / CONTROL', sectionArchitecture: '02 / ARCHITECTURE', sectionDelivery: '03 / DELIVERY', sectionProvenance: '04 / PROVENANCE',
    controlTitle: 'The control plane stays online while the core changes underneath it.',
    controlLead: 'Observe runtime state, traffic, connections, rules, logs, and installed versions from the same local interface.',
    controlAlt: 'Sempre control plane overview', realInterface: 'Sempre Web UI · actual interface',
    architectureTitle: 'One ownership chain. No wrapper stack.',
    architectureLead: 'A single Rust binary owns installation, service registration, validation, deployment, supervision, and rollback.',
    operatorSurface: 'Browser / CLI', interfaceNode: 'Operator interface', supervisorNode: 'Supervisor + rollback', coreNode: 'Managed process',
    nativeDetail: 'Registered directly with each operating system. No NSSM, no third-party service host.',
    platformTitle: 'Same install contract on every supported machine.',
    platformLead: "The installer detects the machine, locks the latest release tag, verifies the matching bundle, then delegates to Sempre's idempotent installer.",
    ready: 'Ready', trustTitle: 'The short command does not shorten the verification chain.',
    trustLead: 'Every target ships with checksums, a CycloneDX SBOM, and GitHub build provenance. Bundle verification happens before the privileged installer starts.',
    verify: 'VERIFY', attestation: 'Attestation', viewRelease: 'View the latest release', footerTagline: 'Any core. Always current. Always running.', releases: 'Releases', security: 'Security',
    independent: 'Independent community project. Not affiliated with proxy core projects.', copied: 'Install command copied', copyCommand: 'Copy install command',
    theme: 'Theme', themeSystem: 'System', themeLight: 'Light', themeDark: 'Dark',
    meta: 'Sempre installs, updates, switches, and supervises proxy cores as a native system service.',
  },
  'zh-CN': {
    title: 'Sempre — 代理核心生命周期管理器',
    skip: '跳到正文', navArchitecture: '工作原理', navPlatforms: '支持平台', navDocs: '使用文档',
    eyebrow: '代理核心生命周期管理', tagline: '任意核心，持续更新，始终运行。',
    lead: '用一个原生系统服务，完成代理核心的安装、更新、切换与守护；所有状态都能在 Web 界面查看和管理。',
    quickStart: '一键安装', oneCommand: '一行命令，自动校验并安装。', checksum: '安装前自动核对 SHA-256',
    coreOption: '核心（可选）', corePlaceholder: 'sing-box@stable', subscriptionOption: '订阅地址（可选）', subscriptionPlaceholder: 'https://example.com/subscription',
    uiOption: 'Web UI', uiDefault: '自动：保留现有 / 首次用官方', uiOfficial: '官方 UI', uiGitHub: 'GitHub Release', uiURL: 'HTTPS ZIP',
    uiSource: 'UI 来源', uiGitHubPlaceholder: 'owner/repo@stable', uiURLPlaceholder: 'https://example.com/sempre-ui.zip', uiDigest: 'UI SHA-256', uiDigestPlaceholder: '64 位校验值',
    inspectScript: '查看安装脚本', releaseNote: '当前为 1.0 前版本 · 二进制尚未签名 · 安装系统服务前请先阅读发行说明',
    signalNative: '直接作为系统服务运行', signalAtomic: '切换失败自动回退', signalReplaceable: '界面与后台互不绑定', signalCrossPlatform: 'Windows、Linux、macOS 都能用',
    signalNativeDetail: '直接接入 Windows SCM、systemd 和 launchd，不需要额外的服务壳。',
    signalAtomicDetail: '新版本通过配置校验后才会启用；启动失败就自动恢复上一个可用版本。',
    signalReplaceableDetail: 'Web UI 可以单独安装或更换，不影响后台服务和正在运行的核心。',
    signalCrossPlatformDetail: '三大系统使用同一套管理方式，同时支持 amd64 和 arm64。',
    overview: '概览', supervisor: '运行守护', running: '运行中', activeCore: '当前核心', enterControlPlane: '查看 Sempre 如何工作',
    sectionControl: '01 / 运行管理', sectionArchitecture: '02 / 工作原理', sectionDelivery: '03 / 安装支持', sectionProvenance: '04 / 发布校验',
    controlTitle: '换核心、升版本时，管理界面始终在线。',
    controlLead: '运行状态、流量、连接、规则、日志和已安装版本，都能在本机同一个界面查看。',
    controlAlt: 'Sempre 管理界面概览', realInterface: 'Sempre Web UI · 实际运行界面',
    architectureTitle: '从下达操作到核心运行，一条链路管到底。',
    architectureLead: '一个 Rust 程序负责安装、注册系统服务、校验配置、部署核心、监控运行状态，并在故障时回滚。',
    operatorSurface: '网页 / 命令行', interfaceNode: '你的操作入口', supervisorNode: '启动、守护、故障回滚', coreNode: '当前运行的核心版本',
    nativeDetail: '直接注册为系统服务，不依赖 NSSM，也不需要第三方服务宿主。',
    platformTitle: '一条安装命令，三大系统都能用。',
    platformLead: '安装脚本会自动识别系统与架构，锁定一个明确的发行版本，校验下载文件，再执行可重复运行的安装流程。',
    ready: '已支持', trustTitle: '命令只有一行，校验一步不少。',
    trustLead: '每个平台的发布包都附带 SHA-256 校验和、CycloneDX 软件物料清单和 GitHub 构建证明；校验通过后，才会执行需要系统权限的安装。',
    verify: '校验', attestation: '构建证明', viewRelease: '查看最新版本', footerTagline: '任意核心，持续更新，始终运行。', releases: '下载', security: '安全说明',
    independent: 'Sempre 是独立社区项目，与任何代理核心项目均无隶属或官方合作关系。', copied: '已复制安装命令', copyCommand: '复制安装命令',
    theme: '主题', themeSystem: '跟随系统', themeLight: '浅色', themeDark: '深色',
    meta: 'Sempre 用一个原生系统服务安装、更新、切换并持续守护代理核心。',
  },
} as const

export type CopyKey = keyof typeof copy.en

export function resolveInitialLocale(saved: string | null, browserLanguage: string): Locale {
  if (saved === 'en' || saved === 'zh-CN') return saved
  return browserLanguage.toLowerCase().startsWith('zh') ? 'zh-CN' : 'en'
}
